;; Three blocks (A B and C) are on the table along with three sprayers
;; (red, green, blue), three paint cans (red, green, blue), a water
;; bucket and a clean brush.  Paint A, B and C red, blue and green,
;; respectively. End with the arm empty and the brush clean.

(define (problem 3)
  (:domain hw5)
  (:objects blockA blockB blockC redSprayer greenSprayer blueSprayer redPaintCan greenPaintCan bluePaintCan waterbucket brush1)
  (:init (arm-empty)
         (block blockA)
         (block blockB)
         (block blockC)
         (on-table blockA)
         (on-table blockB)
         (on-table blockC)
         (clear blockA)
         (clear blockB)
         (clear blockC)
         (sprayer redSprayer red)
         (sprayer greenSprayer green)
         (sprayer blueSprayer blue)
         (on-table redSprayer)
         (on-table greenSprayer)
         (on-table blueSprayer)
         (clear redSprayer)
		     (clear greenSprayer)
		     (clear blueSprayer)
         (paint-can redPaintCan red)
         (paint-can greenPaintCan green)
         (paint-can bluePaintCan blue)
         (on-table redPaintCan)
         (on-table greenPaintCan)
         (on-table bluePaintCan)
         (clear redPaintCan)
         (clear greenPaintCan)
         (clear bluePaintCan)
         (water-bucket waterbucket)
         (on-table waterbucket)
         (clear waterbucket)
         (brush brush1)
         (on-table brush1)
         (clear brush1)
         (clean brush1))
  (:goal (and (arm-empty)
          ;; a is red, b is blue, C is green and the brush is clean
          (color blockA red)
          (color blockB blue)
          (color blockC green)
          (clean brush1)
          )))