;; Block A is on the table, B is on A and C on B.  On the table are a
;; water bucket, a red sprayer, cans of blue and green paint and a
;; clean brush.  The goal is to make A red, B green and C blue and to
;; have A on B, B on C and C on the table and the brush clean and arm
;; empty.

(define (problem 4)
  (:domain hw5)
  (:objects blockA blockB blockC redSprayer bluePaintCan greenPaintCan waterbucket brush1)
  (:init (arm-empty)
  			(block blockA)
  			(block blockB)
  			(block blockC)
  			(on-table blockA)
  			(on blockB blockA)
  			(on blockC blockB)
  			(clear blockC)
  			(sprayer redSprayer red)
  			(on-table redSprayer)
  			(clear redSprayer)
  			(paint-can bluePaintCan blue)
  			(on-table bluePaintCan)
  			(clear bluePaintCan)
  			(paint-can greenPaintCan green)
  			(on-table greenPaintCan)
  			(clear greenPaintCan)
  			(water-bucket waterbucket)
  			(on-table waterbucket)
  			(clear waterbucket)
  			(brush brush1)
  			(on-table brush1)
  			(clear brush1)
  			(clean brush1)
  )
  (:goal (and (arm-empty)
  				(color blockA red)
  				(color blockB green)
  				(color blockC blue)
  				(on blockA blockB)
  				(on blockB blockC)
  				(on-table blockC)
  				(clean brush1)
  )))
